# This workflow will automatically generate documentation for develop branch

name: Contracts Docgen

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - uses: canastro/copy-file-action@master
        name: "copy env file"
        with:
          source: .env.example
          target: .env
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependency
        run: sudo apt-get install graphviz && npm i lerna -g && yarn install
      - name: Run docify
        run: lerna run --scope @popcorn/contracts docify
      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: develop-docgen
          FOLDER: packages/contracts/docgen/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
